sonar.projectKey=skillup-frontend
sonar.projectName=SkillUp Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.host.url=http://172.17.0.3:9000
sonar.token=sqa_21365725c74b2860e9d5bd6bd0f84abf8f2e7de0
